// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnBPIdAUDUzPjVPizG9REzm6qc-rUZ7EQ',
    appId: '1:53934668662:web:d1a54a9ec250d798441857',
    messagingSenderId: '53934668662',
    projectId: 'frot-market',
    authDomain: 'frot-market.firebaseapp.com',
    storageBucket: 'frot-market.firebasestorage.app',
    measurementId: 'G-1P0CFRM75H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLEiuKsZS4SXIV1jNwiCVZsSPtnyZLKTk',
    appId: '1:53934668662:android:892062b52ee16447441857',
    messagingSenderId: '53934668662',
    projectId: 'frot-market',
    storageBucket: 'frot-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSfxPSvInHxvEPP9_fUXXtNbwlGZvLutM',
    appId: '1:53934668662:ios:0fc5df572793125a441857',
    messagingSenderId: '53934668662',
    projectId: 'frot-market',
    storageBucket: 'frot-market.firebasestorage.app',
    iosBundleId: 'com.example.fruitesMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSfxPSvInHxvEPP9_fUXXtNbwlGZvLutM',
    appId: '1:53934668662:ios:0fc5df572793125a441857',
    messagingSenderId: '53934668662',
    projectId: 'frot-market',
    storageBucket: 'frot-market.firebasestorage.app',
    iosBundleId: 'com.example.fruitesMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnBPIdAUDUzPjVPizG9REzm6qc-rUZ7EQ',
    appId: '1:53934668662:web:4e756dce8d0dcaa1441857',
    messagingSenderId: '53934668662',
    projectId: 'frot-market',
    authDomain: 'frot-market.firebaseapp.com',
    storageBucket: 'frot-market.firebasestorage.app',
    measurementId: 'G-4MBLQ08YSC',
  );
}
